# -*- coding: utf-8 -*-
"""python for data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Gv-vZ4c1pk_VXvE07qsHuLdAWOko4G4U
"""

import pandas as pd

bank_client_df = pd.DataFrame({'Client ID': [111, 222, 333, 444],
                             'Name': ['Ali', 'Hassan', 'Kamran', 'Ahtsham'],
                             'Net Worth [$]': [6000, 1000, 1999, 10000],
                             'Years with Bank': [3,1,7,6]})

bank_client_df

rich_df = bank_client_df[ bank_client_df['Net Worth [$]'] >= 5000]
rich_df

networth_combined = rich_df['Net Worth [$]'].sum()
networth_combined

total_years = rich_df['Years with Bank'].sum()
total_years

house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

def networth_update(balance):
  return balance * 1.2

bank_client_df['Net Worth [$]'].apply(networth_update)

bank_client_df['Name'].apply(len)

stocks_df = pd.DataFrame({'Stock Ticker Symbol':['AAPL', 'AMZN', 'T'],
                         'Price per Share [$]': [4, 2, 3],
                         'Number of stocks': [3,4,6]})

def triples(prices):
  return prices * 3 + 200

stocks_df['Price per Share [$]'].apply(triples).sum()

bank_client_df.sort_values(by = 'Years with Bank', inplace = True)

bank_client_df

df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']},
                    index=[0,1,2,3])
df1

df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']},
                    index=[4,5,6,7])

df2

df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']},
                    index=[8,9,10,11])
df3

pd.concat([df1, df2, df3])

Bank_df_1 = pd.DataFrame({'Client ID':[1,2,3,4,5],
                          'First Name':['Ahtsham','Ali','Imran','Rizwan','Haad'],
                          'Last Name':['Shah', 'Hassan', 'Hussain', 'Ali', 'Kazmi'],
                          }, index=[0,1,2,3,4])
Bank_df_1

Bank_df_2 = pd.DataFrame({'Client ID':[6,7,8,9,10],
                          'First Name':['Kamran','Fazeel','Aqib','Awais','Junaid'],
                          'Last Name':['Haider', 'Sial', 'Qureshi', 'Khan', 'Raja'],
                          }, index=[5,6,7,8,9])

Bank_df_2

all_clients_df = pd.concat([Bank_df_1, Bank_df_2])

my_data_df = pd.DataFrame({'Client ID':[11],
                           'First Name': ['Muhammad'],
                           'Last Name': ['Naeem']},
                          index=[11])
my_data_df

new_df = pd.concat([all_clients_df, my_data_df])

new_df

salaries_df = pd.DataFrame({
    'Client ID': [1,2,3,4,5,6,7,8,9,10,11],
    'Annual Salary [$]': [3400,2333,1212,1000,2000,2300,4000,34,533,532,10024]
})

salaries_df

bank_df_all = pd.merge(new_df, salaries_df, on='Client ID')
bank_df_all

bank_df_all.columns

bank_df_all.head()

